ci: test 401 in docker /timer

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -21,8 +21,14 @@ jobs:
     - name: Run Docker
       run: docker run -d --name dead_man_switch -p 3000:3000 dead_man_switch
 
+    - name: Test Docker
+      run: |
+        sleep 10 # sleep for 10 seconds to allow the server to start
+        response=$(curl -s -o /dev/null -w "%{http_code}" localhost:3000/timer)
+        if [ "$response" -ne 401 ]; then
+            echo "Expected UNAUTHORIZED error, but got $response"
+            exit 1
+        fi
+
     - name: Display Docker container logs
       run: docker logs dead_man_switch
-
-    - name: Test Docker
-      run: curl --fail localhost:3000/ || exit 1
